# Generated by Django 3.1 on 2020-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
