# Generated by Django 3.0.8 on 2020-07-10 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Followed_User', to='users.User')),
                ('following_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following_User', to='users.User')),
            ],
            options={
                'db_table': 'following',
            },
        ),
    ]
