# Generated by Django 3.0.8 on 2020-07-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='followed_user_id',
            new_name='followed_user',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='following_user_id',
            new_name='following_user',
        ),
    ]
