# Generated by Django 3.1 on 2020-09-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_users_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
    ]
