# Generated by Django 3.1.3 on 2020-11-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201110_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
