# Generated by Django 3.0.7 on 2020-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
    ]
