# Generated by Django 3.0.8 on 2020-07-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='members',
        ),
    ]
