# Generated by Django 3.0.8 on 2020-07-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200715_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_user', to='user.User')),
                ('followee_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followee_user', to='user.User')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='user_follow', through='user.Follow', to='user.User'),
        ),
    ]
