# Generated by Django 3.0.8 on 2020-07-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200716_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='_user_follow_+', through='user.Follow', to='user.User'),
        ),
    ]
