# Generated by Django 3.1.3 on 2020-12-09 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_auto_20201205_1213'),
        ('user', '0004_auto_20201208_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('liked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
