# Generated by Django 3.1.5 on 2021-02-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_auto_20210202_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=500)),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.userinfo')),
            ],
            options={
                'db_table': 'userposting',
            },
        ),
    ]
