# Generated by Django 3.1.5 on 2021-02-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0003_auto_20210207_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlike',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='userlike',
            old_name='user_id',
            new_name='user',
        ),
    ]
