# Generated by Django 3.1.5 on 2021-02-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_follow'),
        ('Posting', '0004_auto_20210207_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditonalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addcomment', models.CharField(max_length=200)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posting.usercomment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userinfo')),
            ],
        ),
    ]
