# Generated by Django 3.1 on 2020-09-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserManager',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
