# Generated by Django 3.1.3 on 2020-11-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201105_1045'),
        ('posting', '0003_auto_20201108_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
