# Generated by Django 3.1.3 on 2020-11-08 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_key', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('post_desc', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
                ('location_info', models.CharField(max_length=500, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('updated_pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-updated_pub_date'],
            },
        ),
    ]
