# Generated by Django 3.1.3 on 2020-11-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201109_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
