# Generated by Django 3.1.3 on 2020-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201110_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['updated_at']},
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='upload_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='img_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='post_images',
        ),
    ]
