# Generated by Django 3.1.3 on 2020-11-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201110_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_pub_date',
            new_name='updated_at',
        ),
    ]
