# Generated by Django 3.1.3 on 2020-11-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201111_1458'),
        ('post', '0010_auto_20201111_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_post', to='user.User'),
        ),
    ]
