# Generated by Django 3.1.3 on 2020-11-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
