# Generated by Django 3.1.3 on 2020-11-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20201109_1138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
