# Generated by Django 3.1.4 on 2020-12-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20201204_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='username',
        ),
    ]
