# Generated by Django 3.1.4 on 2020-12-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_boardcomment_posting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardcomment',
            old_name='comment_itme',
            new_name='itme',
        ),
        migrations.RenameField(
            model_name='boardcomment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='boardcomment',
            old_name='comment_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='boardposting',
            old_name='posting_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='boardposting',
            old_name='posting_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='boardposting',
            old_name='posting_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='boardposting',
            old_name='posting_username',
            new_name='username',
        ),
    ]
