# Generated by Django 3.1.4 on 2020-12-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20201204_0503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='username',
            new_name='user',
        ),
    ]
