# Generated by Django 3.1.4 on 2020-12-04 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20201204_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='submit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
