# Generated by Django 3.1.4 on 2020-12-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20201204_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
