# Generated by Django 3.1.4 on 2020-12-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20201204_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='submit_time',
        ),
        migrations.AddField(
            model_name='board',
            name='username',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
