# Generated by Django 3.1.4 on 2020-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20201204_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
