# Generated by Django 3.1.7 on 2021-03-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210309_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followee',
            new_name='from_follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='to_follow',
        ),
    ]
