# Generated by Django 3.0.8 on 2020-08-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200807_1250'),
        ('Posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_time', models.TimeField(auto_now=True)),
                ('comment', models.CharField(max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posting.Posting')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Account')),
            ],
        ),
    ]
