# Generated by Django 3.0.7 on 2020-07-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love',
            old_name='loveTF',
            new_name='is_like',
        ),
    ]
