# Generated by Django 3.0.8 on 2020-08-07 14:04

from django.db import migrations, models
import user.validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, validators=[user.validator.validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[user.validator.validate_password]),
        ),
    ]
