# Generated by Django 3.1.7 on 2021-03-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210305_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pswd',
        ),
    ]
