# Generated by Django 3.1.7 on 2021-03-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20210307_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_like',
            new_name='user',
        ),
    ]
