# Generated by Django 3.1.7 on 2021-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20210307_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='user_like',
            field=models.CharField(default='', max_length=10),
        ),
    ]
