# Generated by Django 3.1.7 on 2021-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_like_user_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user_like',
            field=models.CharField(default='좋아요', max_length=10),
        ),
    ]
