# Generated by Django 3.1.5 on 2021-01-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='이메일')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'users',
                'ordering': ('email',),
            },
        ),
    ]
