# Generated by Django 3.1.4 on 2020-12-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='사용자명')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('mobile', models.CharField(max_length=20, verbose_name='휴대폰')),
                ('email', models.CharField(max_length=30, verbose_name='이메일')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
                'db_table': 'users',
                'ordering': ('username',),
            },
        ),
    ]
