# Generated by Django 3.1.5 on 2021-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210108_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
