# Generated by Django 3.1.3 on 2020-11-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_account'),
        ('posting', '0005_auto_20201110_0647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
