# Generated by Django 3.1.3 on 2020-11-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20201111_0459'),
        ('user', '0006_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Accounts',
        ),
    ]
