# Generated by Django 3.1.3 on 2020-11-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20201111_1307'),
        ('user', '0007_auto_20201111_0459'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accounts',
            table='accounts',
        ),
        migrations.CreateModel(
            name='AccountBroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.accounts')),
                ('broad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.broads')),
            ],
            options={
                'db_table': 'accounts_borads',
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='broad',
            field=models.ManyToManyField(through='user.AccountBroad', to='posting.Broads'),
        ),
    ]
