# Generated by Django 3.1.3 on 2020-11-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201111_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='broad',
        ),
        migrations.DeleteModel(
            name='AccountBroad',
        ),
    ]
