# Generated by Django 3.1.3 on 2020-11-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_broads_like'),
        ('user', '0009_auto_20201112_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBroad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.accounts')),
                ('broad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.broads')),
            ],
            options={
                'db_table': 'accounts_borads',
            },
        ),
    ]
