# Generated by Django 3.1.3 on 2020-11-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_auto_20201112_0529'),
        ('user', '0010_accountbroad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountBroad',
            new_name='Broadlikes',
        ),
    ]
