# Generated by Django 3.1.4 on 2020-12-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_name',
            new_name='name',
        ),
    ]
