# Generated by Django 3.1.4 on 2020-12-06 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_tiem', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_body', models.CharField(max_length=100)),
                ('board_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
