# Generated by Django 3.1.5 on 2021-02-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='follower_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following', to='user.user')),
            ],
            options={
                'db_table': 'following',
            },
        ),
    ]
