# Generated by Django 3.1 on 2020-08-09 03:32

from django.db import migrations, models
import user.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, validators=[user.validation.Validate_email])),
                ('phone', models.CharField(max_length=30, validators=[user.validation.Validation_phone])),
                ('password', models.CharField(max_length=300, validators=[user.validation.Validate_password])),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
