# Generated by Django 3.1 on 2020-08-09 03:37

from django.db import migrations, models
import user.validation


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200809_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[user.validation.Validate_email]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, validators=[user.validation.Validate_password]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, validators=[user.validation.Validation_phone]),
        ),
    ]
