# Generated by Django 3.0.8 on 2020-07-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200710_1254'),
        ('posts', '0004_auto_20200708_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hearts',
            new_name='likes',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
    ]
