# Generated by Django 3.0.8 on 2020-08-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20200803_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
