# Generated by Django 3.0.8 on 2020-08-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
