# Generated by Django 3.1.3 on 2020-11-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
