# Generated by Django 3.1.2 on 2020-10-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='contents',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
