# Generated by Django 3.1.5 on 2021-02-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
