# Generated by Django 3.1 on 2020-09-03 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_num', models.IntegerField()),
                ('email', models.CharField(max_length=100, null=True)),
                ('pw', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='posting',
            name='name',
        ),
        migrations.AlterField(
            model_name='posting',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.user'),
        ),
    ]
