# Generated by Django 3.1 on 2020-09-03 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200902_1345'),
        ('posting', '0002_auto_20200903_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='image_url',
        ),
        migrations.AddField(
            model_name='posting',
            name='contents',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='img_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
