# Generated by Django 3.1 on 2020-09-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200903_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='writer_people',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
