# Generated by Django 3.1.4 on 2020-12-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posts')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
