# Generated by Django 3.1 on 2020-08-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(help_text='이메일', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='사용자 이름', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(help_text='비밀번호', max_length=400),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(help_text='전화번호', max_length=200),
        ),
    ]
