# Generated by Django 3.1.2 on 2020-11-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
