# Generated by Django 3.1.2 on 2020-11-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20201108_2246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='board',
        ),
    ]
