# Generated by Django 3.1.2 on 2020-11-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20201110_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_url',
        ),
    ]
