# Generated by Django 3.1.2 on 2020-11-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
