# Generated by Django 3.1.3 on 2020-11-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20201108_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='user_name',
        ),
    ]
