# Generated by Django 3.1.1 on 2020-10-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='account',
        ),
    ]
