# Generated by Django 3.0.8 on 2020-08-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200811_1952'),
        ('posting', '0004_auto_20200810_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
