# Generated by Django 3.1.3 on 2020-11-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
