# Generated by Django 3.1.3 on 2020-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.IntegerField(null=True),
        ),
    ]
