# Generated by Django 3.1 on 2020-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20200904_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='images_url',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='images',
            new_name='images_url',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='user',
            new_name='writer',
        ),
        migrations.AddField(
            model_name='posting',
            name='contents',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
