# Generated by Django 3.1 on 2020-09-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200904_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
