# Generated by Django 3.1.3 on 2020-11-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
