# Generated by Django 3.1.3 on 2020-11-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_password',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
