# Generated by Django 3.1.3 on 2020-11-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201105_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_number',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_password',
            field=models.CharField(default='', max_length=40),
        ),
    ]
