# Generated by Django 3.1.3 on 2020-11-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201105_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_password',
            field=models.CharField(max_length=40),
        ),
    ]
