# Generated by Django 3.1.3 on 2020-11-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201106_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_number',
            field=models.IntegerField(default=''),
        ),
    ]
