# Generated by Django 3.1.3 on 2020-11-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201106_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_password',
            field=models.IntegerField(default=''),
        ),
    ]
