# Generated by Django 3.1.3 on 2020-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201106_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_number',
            field=models.CharField(default='', max_length=40),
        ),
    ]
