# Generated by Django 3.1.1 on 2020-10-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20201011_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='created_at',
        ),
    ]
