# Generated by Django 3.1.3 on 2020-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='time',
            new_name='created',
        ),
        migrations.AddField(
            model_name='posting',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
