# Generated by Django 3.1.3 on 2020-11-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20201109_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=models.TextField(default='', null=True),
        ),
    ]
