# Generated by Django 3.1.3 on 2020-11-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
