# Generated by Django 3.1.1 on 2020-10-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_image_urls_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image_urls',
            table='image_urls',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
