# Generated by Django 3.1.1 on 2020-10-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201011_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Image_urls',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
