# Generated by Django 3.1.1 on 2020-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201013_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(null=True, related_name='follows', through='user.Follow', to='user.User'),
        ),
    ]
