# Generated by Django 3.1 on 2020-09-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_Time',
        ),
    ]
