# Generated by Django 3.1 on 2020-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0002_remove_post_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pubTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
