# Generated by Django 3.1 on 2020-09-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.URLField(),
        ),
    ]
