# Generated by Django 3.1.1 on 2020-09-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20200906_1548'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
        migrations.AlterModelTable(
            name='postmedia',
            table='postmedia',
        ),
    ]
