# Generated by Django 3.1.1 on 2020-09-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200909_0251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photos',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.postmedia')),
                ('re_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.comment')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
