# Generated by Django 3.1.4 on 2020-12-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201208_0905'),
        ('post', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(related_name='liker_post', to='user.User'),
        ),
    ]
