# Generated by Django 3.1.4 on 2020-12-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201210_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2020-12-10 01:57:15.988331'),
            preserve_default=False,
        ),
    ]
