# Generated by Django 3.1.2 on 2020-10-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('followers', models.IntegerField(default=0)),
                ('followees', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_from_account', to='user.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_to_account', to='user.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='relations',
            field=models.ManyToManyField(related_name='_account_relations_+', through='user.Relation', to='user.Account'),
        ),
    ]
