# Generated by Django 3.1.2 on 2020-10-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_from_account', to='user.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_to_account', to='user.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='relations',
            field=models.ManyToManyField(related_name='_account_relations_+', through='user.Relation', to='user.Account'),
        ),
    ]
