# Generated by Django 3.1.2 on 2020-10-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201013_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
