# Generated by Django 3.1.3 on 2020-11-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='postedtime',
            new_name='created_at',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='posting',
            table='postings',
        ),
    ]
