# Generated by Django 3.1.3 on 2020-11-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201110_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postedtime',
            new_name='created_at',
        ),
    ]
