# Generated by Django 3.1.3 on 2020-12-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
    ]
