# Generated by Django 3.1.3 on 2020-12-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_signup_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='categories',
        ),
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='tel',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='signup',
            table='signups',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
