# Generated by Django 3.1.3 on 2020-12-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201206_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
