# Generated by Django 3.1.4 on 2020-12-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
