# Generated by Django 3.1.4 on 2020-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201208_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_type',
            field=models.CharField(default='', max_length=5),
        ),
    ]
