# Generated by Django 3.1.4 on 2020-12-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201208_0644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
        migrations.AlterModelTable(
            name='account',
            table='User',
        ),
    ]
