# Generated by Django 3.1.4 on 2020-12-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201208_0702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='User',
        ),
        migrations.AlterModelTable(
            name='user',
            table='we_users',
        ),
    ]
