# Generated by Django 3.1.4 on 2020-12-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201208_0706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
