# Generated by Django 3.1.4 on 2020-12-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
