# Generated by Django 3.1.2 on 2020-10-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True, unique=True)),
                ('full_name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
