# Generated by Django 3.1.3 on 2020-11-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20201109_1934'),
        ('user', '0003_auto_20201109_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posting',
            field=models.ManyToManyField(related_name='likes', through='user.Like', to='posting.Posting'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='user.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='user.user')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='_user_follow_+', through='user.Follow', to='user.User'),
        ),
    ]
