# Generated by Django 3.1.3 on 2020-11-08 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_followlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followlist',
            name='follow_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_to_user', to='user.user'),
        ),
        migrations.AlterField(
            model_name='followlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_from_user', to='user.user'),
        ),
    ]
