# Generated by Django 3.1.3 on 2020-11-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20201109_1901'),
        ('user', '0006_auto_20201110_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(null=True, through='user.FollowList', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(null=True, related_name='like_user', to='posting.Post'),
        ),
    ]
