# Generated by Django 3.1.2 on 2020-10-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='tel',
            new_name='phone_number',
        ),
    ]
