# Generated by Django 3.1.5 on 2021-02-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='ussers',
        ),
    ]
