# Generated by Django 3.1.5 on 2021-02-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_follow'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(through='posting.Follow', to='user.User'),
        ),
    ]
