# Generated by Django 3.1.7 on 2021-03-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210308_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='username',
            new_name='user',
        ),
    ]
