# Generated by Django 3.1.3 on 2020-11-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20201112_1510'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
    ]
