# Generated by Django 3.1.4 on 2020-12-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_signin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Users',
        ),
        migrations.DeleteModel(
            name='Signin',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
