# Generated by Django 3.1.7 on 2021-03-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
    ]
