# Generated by Django 3.1.7 on 2021-03-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20210307_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
    ]
