# Generated by Django 3.1.7 on 2021-03-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_remove_follow_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
