# Generated by Django 3.1.5 on 2021-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
