# Generated by Django 3.1.5 on 2021-02-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
