# Generated by Django 3.1.4 on 2021-01-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_commentbycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbycomment',
            name='content',
            field=models.CharField(default='lala', max_length=100),
            preserve_default=False,
        ),
    ]
