# Generated by Django 3.1.4 on 2021-01-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commentbycomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='fasdfawefawef.jpg', max_length=2000),
            preserve_default=False,
        ),
    ]
