# Generated by Django 3.1.1 on 2020-10-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='response_to',
            field=models.IntegerField(null=True),
        ),
    ]
