# Generated by Django 3.1.7 on 2021-03-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210305_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='user_name',
        ),
    ]
