# Generated by Django 3.1.7 on 2021-03-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210305_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pw',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
