# Generated by Django 3.1.5 on 2021-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='writer',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
