# Generated by Django 3.1.5 on 2021-02-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
