# Generated by Django 3.1.5 on 2021-02-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_like_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
    ]
