# Generated by Django 3.1.5 on 2021-02-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_remove_comment_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='writer',
        ),
    ]
