# Generated by Django 3.1.5 on 2021-02-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_remove_posting_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
