# Generated by Django 3.1.3 on 2020-11-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet_content',
            new_name='comment_content',
        ),
    ]
