# Generated by Django 3.1.3 on 2020-11-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20201107_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
