# Generated by Django 3.1.3 on 2020-11-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20201110_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='posting',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
