# Generated by Django 3.1.4 on 2021-01-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210106_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tel_num',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
