# Generated by Django 3.1.5 on 2021-02-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='image_usl',
            new_name='image_url',
        ),
    ]
