# Generated by Django 3.1.5 on 2021-02-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20210207_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
    ]
