# Generated by Django 3.1.5 on 2021-02-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210204_0409'),
        ('posting', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostingLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Like',
            },
        ),
        migrations.AddField(
            model_name='posting',
            name='like',
            field=models.ManyToManyField(related_name='like', through='posting.UserPostingLike', to='user.User'),
        ),
    ]
