# Generated by Django 3.1.5 on 2021-02-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20210208_2113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpostinglike',
            table='UserPostingLike',
        ),
    ]
