# Generated by Django 3.1.5 on 2021-02-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20210208_2118'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpostinglike',
            table='Like',
        ),
    ]
