# Generated by Django 3.1.5 on 2021-02-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0008_auto_20210208_2119'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpostinglike',
            table='UserPostingLike',
        ),
    ]
