# Generated by Django 3.1.5 on 2021-02-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210204_0409'),
        ('posting', '0009_auto_20210208_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostinglike',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting', unique=True),
        ),
        migrations.AlterField(
            model_name='userpostinglike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', unique=True),
        ),
    ]
