# Generated by Django 3.1.5 on 2021-01-31 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=14)),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8, '8자 이상의 비밀번호를 입력하세요.')])),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
