# Generated by Django 3.1.5 on 2021-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=100),
        ),
    ]
