# Generated by Django 3.1.5 on 2021-02-01 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210131_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(8, '8자 이상의 비밀번호를 입력하세요.')]),
        ),
    ]
