# Generated by Django 3.1.5 on 2021-02-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210201_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=2, max_length=14),
            preserve_default=False,
        ),
    ]
