# Generated by Django 3.1.5 on 2021-02-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='create_at',
        ),
    ]
