# Generated by Django 3.1.5 on 2021-02-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_userlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
