# Generated by Django 3.1.5 on 2021-02-08 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_like_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=datetime.datetime(2021, 2, 8, 14, 31, 29, 768514)),
            preserve_default=datetime.datetime(2021, 2, 8, 14, 31, 29, 768514),
        ),
        migrations.AddField(
            model_name='posting',
            name='like_user',
            field=models.ManyToManyField(through='posting.Like', to='posting.UserLike'),
        ),
    ]
