# Generated by Django 3.1.5 on 2021-02-08 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_auto_20210208_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_user',
            new_name='userlike',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='like_user',
            new_name='userlike',
        ),
        migrations.RenameField(
            model_name='userlike',
            old_name='like_user',
            new_name='userlike',
        ),
        migrations.AlterField(
            model_name='like',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=datetime.datetime(2021, 2, 8, 14, 43, 53, 298728)),
        ),
    ]
