# Generated by Django 3.1.3 on 2020-11-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.accounts'),
        ),
        migrations.AddField(
            model_name='broads',
            name='like',
            field=models.ManyToManyField(related_name='likes', through='user.Broadlikes', to='user.Accounts'),
        ),
        migrations.AddField(
            model_name='broads',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.accounts'),
        ),
    ]
