# Generated by Django 3.1.3 on 2020-11-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201105_1045'),
        ('posting', '0002_auto_20201107_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broad',
            name='content',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('broad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.broad')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
