# Generated by Django 3.1.3 on 2020-11-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20201113_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broads',
            old_name='likes_num',
            new_name='likecount',
        ),
    ]
