# Generated by Django 3.1.3 on 2020-11-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_account'),
        ('posting', '0004_auto_20201109_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broad',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account'),
        ),
    ]
