# Generated by Django 3.1.3 on 2020-11-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_users'),
        ('posting', '0005_auto_20201110_0647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Broad',
            new_name='Broads',
        ),
    ]
