# Generated by Django 3.1.3 on 2020-11-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20201111_0459'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='broads',
            table='broads',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
