# Generated by Django 3.1.3 on 2020-11-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201112_0414'),
        ('posting', '0007_auto_20201111_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='broads',
            name='like',
            field=models.ManyToManyField(related_name='like', to='user.Accounts'),
        ),
    ]
