# Generated by Django 3.1.3 on 2020-11-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_accountbroad'),
        ('posting', '0008_broads_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broads',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='user.Accounts'),
        ),
    ]
