# Generated by Django 3.1 on 2020-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
