# Generated by Django 3.1.4 on 2021-01-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comment'),
        ),
    ]
