# Generated by Django 3.1.5 on 2021-02-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210207_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_time',
            new_name='date_time',
        ),
    ]
