# Generated by Django 3.1.5 on 2021-02-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
