# Generated by Django 3.1.5 on 2021-02-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210210_2200'),
        ('posts', '0007_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replies', to='user.user'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replies', to='posts.comment'),
        ),
    ]
