# Generated by Django 3.1.4 on 2020-12-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='default@gmail.com', max_length=30, unique=True, verbose_name='이메일')),
                ('title', models.CharField(default='', max_length=100, unique=True)),
                ('content', models.TextField(default='')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(default='', max_length=2800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'postings',
                'ordering': ('-created_dt',),
            },
        ),
    ]
