# Generated by Django 3.1.4 on 2020-12-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(default='default@gmail.com', max_length=30, verbose_name='이메일'),
        ),
    ]
