# Generated by Django 3.1.5 on 2021-01-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
    ]
