# Generated by Django 3.1.5 on 2021-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_post_like_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='', max_length=2800, null=True),
        ),
    ]
