# Generated by Django 3.0.8 on 2020-08-01 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='enter number without - ', regex='^\\d{3}-\\d{4}-\\d{4}$')])),
                ('password', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='include character and number with at least 8 characters', regex='^(?=.*[a-z])(?=.*\\d)[a-z\\d]{8,}$')])),
            ],
        ),
    ]
