# Generated by Django 3.1 on 2020-08-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200809_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='user',
        ),
    ]
