# Generated by Django 3.1.3 on 2020-11-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20201109_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
