# Generated by Django 3.1.3 on 2020-11-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20201109_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posting.comment'),
        ),
    ]
