# Generated by Django 3.1.5 on 2021-02-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210207_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posting',
        ),
    ]
