# Generated by Django 3.1.5 on 2021-02-09 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210204_0759'),
        ('posting', '0003_auto_20210209_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.post')),
            ],
        ),
    ]
