# Generated by Django 3.1.5 on 2021-02-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
    ]
