# Generated by Django 3.1.5 on 2021-02-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20210209_0541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
