# Generated by Django 3.1.5 on 2021-02-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_follow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
    ]
