# Generated by Django 3.0.8 on 2020-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('passWord', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
