# Generated by Django 3.0.8 on 2020-08-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20200807_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='passWord',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='phoneNum',
            new_name='phone_num',
        ),
    ]
