# Generated by Django 3.1.7 on 2021-03-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_reply'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reply',
            table='replies',
        ),
    ]
