# Generated by Django 3.1.7 on 2021-03-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
