# Generated by Django 3.1.7 on 2021-03-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20210305_0727'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
