# Generated by Django 3.1.7 on 2021-03-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210304_1120'),
        ('posting', '0005_auto_20210305_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'db_table': 'posting_likes',
            },
        ),
        migrations.AddField(
            model_name='posting',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_postings', through='posting.PostingLike', to='account.User'),
        ),
    ]
