# Generated by Django 3.0.8 on 2020-07-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_thumbs_up'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='thumbs',
            table='thumbs',
        ),
    ]
