# Generated by Django 3.1.3 on 2020-11-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thumbsup',
            table='thumbup',
        ),
    ]
