# Generated by Django 3.1.3 on 2020-11-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs_up', '0002_auto_20201107_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbsup',
            name='good',
        ),
        migrations.AlterModelTable(
            name='thumbsup',
            table='thumbs_up',
        ),
    ]
