# Generated by Django 3.1.4 on 2021-01-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_users_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'post_register',
            },
        ),
        migrations.CreateModel(
            name='Post_express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('upload_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('post_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.post_register')),
            ],
            options={
                'db_table': 'post_express',
            },
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.post_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'love',
            },
        ),
        migrations.CreateModel(
            name='Comments_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('post_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.post_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'comments_register',
            },
        ),
    ]
