# Generated by Django 3.1.4 on 2020-12-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=100)),
                ('post_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'post_express',
            },
        ),
        migrations.CreateModel(
            name='Post_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now=True)),
                ('upadte_time', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'db_table': 'post_register',
            },
        ),
    ]
