# Generated by Django 3.1.4 on 2021-01-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_commentsincomments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentsincomments',
            table='commentsincomments',
        ),
    ]
