# Generated by Django 3.1 on 2020-09-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200903_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pub_content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
