# Generated by Django 3.1.1 on 2020-10-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
    ]
