# Generated by Django 3.1.1 on 2020-10-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201013_1537'),
        ('posting', '0005_auto_20201013_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ManyToManyField(through='posting.Like', to='user.User'),
        ),
    ]
