# Generated by Django 3.1.1 on 2020-10-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0006_auto_20201013_2102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='like_check',
        ),
    ]
