# Generated by Django 3.1.1 on 2020-10-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20201015_1523'),
        ('posting', '0007_auto_20201013_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_like',
            field=models.ManyToManyField(related_name='user_like', through='posting.Like', to='user.User'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posting.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
