# Generated by Django 3.1.5 on 2021-02-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
