# Generated by Django 3.1.5 on 2021-02-03 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210201_1048'),
        ('posting', '0003_auto_20210202_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.accounts')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
            ],
            options={
                'db_table': 'like_postings',
            },
        ),
    ]
