# Generated by Django 3.1.5 on 2021-02-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_comment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.IntegerField(default=None),
        ),
    ]
