# Generated by Django 3.1.4 on 2020-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phonenumber', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=70)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
