# Generated by Django 3.0.8 on 2020-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_co', models.CharField(max_length=50)),
                ('text_co', models.CharField(max_length=300)),
                ('created_co', models.DateTimeField(auto_now_add=True)),
                ('updated_co', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
