# Generated by Django 3.1.3 on 2020-11-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=12)),
                ('password', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
