# Generated by Django 3.0.8 on 2020-08-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200803_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
