# Generated by Django 3.1.1 on 2020-10-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posting',
            table='postings',
        ),
    ]
