# Generated by Django 3.1.1 on 2020-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_auto_20201010_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thread_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
