# Generated by Django 3.1.1 on 2020-10-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_comment_thread_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
