# Generated by Django 3.1.1 on 2020-10-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201012_0634'),
        ('posting', '0007_remove_posting_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PostingLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_like', to='posting.posting')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='user.user')),
            ],
            options={
                'db_table': 'postings_likes',
            },
        ),
        migrations.AddField(
            model_name='posting',
            name='like',
            field=models.ManyToManyField(related_name='like_posting', through='posting.PostingLike', to='user.User'),
        ),
    ]
