# Generated by Django 3.1.1 on 2020-10-12 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comments'),
        ),
    ]
