# Generated by Django 3.1.1 on 2020-10-12 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='write_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='write_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
