# Generated by Django 3.1.1 on 2020-10-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20201012_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='post.posts'),
        ),
    ]
