# Generated by Django 3.1.1 on 2020-10-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('post', '0008_auto_20201012_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('write_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.users')),
            ],
        ),
    ]
