# Generated by Django 3.1.7 on 2021-03-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210309_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_by_from_user', to='account.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_by_to_user', to='account.user')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(through='account.Follow', to='account.User'),
        ),
    ]
