# Generated by Django 3.1.7 on 2021-03-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210310_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('from_user', 'to_user')},
        ),
    ]
