# Generated by Django 3.1.5 on 2021-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
