# Generated by Django 3.1.5 on 2021-01-28 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210128_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.id'),
        ),
    ]
