# Generated by Django 3.1.5 on 2021-01-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210128_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.RemoveField(
            model_name='password',
            name='ids',
        ),
        migrations.DeleteModel(
            name='Id',
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
