# Generated by Django 3.1 on 2020-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_numbers',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
