# Generated by Django 3.1 on 2020-09-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200905_1125'),
        ('account', '0002_auto_20200901_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
