# Generated by Django 3.1 on 2020-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phon_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
