# Generated by Django 3.1 on 2020-09-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_phon_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phon_number',
            field=models.CharField(max_length=100),
        ),
    ]
