# Generated by Django 3.1 on 2020-09-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
        ('user', '0003_auto_20200904_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
