# Generated by Django 3.1.5 on 2021-02-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='Phone_number',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
    ]
