# Generated by Django 3.1.5 on 2021-02-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPassword',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
