# Generated by Django 3.1.5 on 2021-02-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210201_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
