# Generated by Django 3.0.8 on 2020-08-03 12:14

import User.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, validators=[User.validation.validate_email])),
                ('password', models.CharField(max_length=300, unique=True, validators=[User.validation.validate_password])),
            ],
        ),
    ]
