# Generated by Django 3.0.8 on 2020-08-03 12:27

import User.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, validators=[User.validation.validate_password]),
        ),
    ]
