# Generated by Django 3.1.3 on 2020-11-05 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
