# Generated by Django 3.1.3 on 2020-11-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20201105_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='article',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
