# Generated by Django 3.1.3 on 2020-11-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20201107_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_parent_content', to='posting.contents'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_content', to='posting.contents'),
        ),
    ]
