# Generated by Django 3.1.3 on 2020-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login_id', models.CharField(max_length=50, unique=True)),
                ('user_mobile_number', models.CharField(max_length=13, unique=True)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
