# Generated by Django 3.1.3 on 2020-11-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='signups',
        ),
    ]
