# Generated by Django 3.1.3 on 2020-11-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201105_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_login_id',
            new_name='login_id',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_mobile_number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='user_password',
            new_name='password',
        ),
    ]
