# Generated by Django 3.1.2 on 2020-10-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201015_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='comment_time',
        ),
    ]
