# Generated by Django 3.1.2 on 2020-10-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phonenumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
