# Generated by Django 3.1.2 on 2020-10-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201012_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phonenumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
