# Generated by Django 3.0.8 on 2020-08-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200805_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='email',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
