# Generated by Django 3.1.7 on 2021-03-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210304_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
