# Generated by Django 3.1.7 on 2021-03-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20210306_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='user',
        ),
    ]
