# Generated by Django 3.1.5 on 2021-02-01 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('010[1-9]\\d{6,7}')]),
        ),
    ]
