# Generated by Django 3.0.3 on 2020-08-01 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('69c6ef09-dbca-4168-b4d8-d6165a3c13cf'), editable=False, primary_key=True, serialize=False)),
                ('phone_or_email', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(editable=False, max_length=32)),
                ('username', models.CharField(editable=False, max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
