# Generated by Django 3.1.5 on 2021-02-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posting_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting'),
        ),
    ]
