# Generated by Django 3.1.5 on 2021-02-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210204_1043'),
        ('posting', '0005_auto_20210208_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('like_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('posting_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
            ],
        ),
    ]
