# Generated by Django 3.1.5 on 2021-02-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20210204_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
