# Generated by Django 3.1.5 on 2021-02-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='to_user',
        ),
    ]
