# Generated by Django 3.1.5 on 2021-02-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_auto_20210205_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment_body', models.TextField(max_length=10000)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.comment')),
            ],
            options={
                'db_table': 'commentoncomments',
            },
        ),
    ]
