# Generated by Django 2.2.5 on 2020-12-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image_url',
            new_name='img_url',
        ),
    ]
