# Generated by Django 3.1.4 on 2021-01-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_count_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_likes',
        ),
    ]
