# Generated by Django 3.1.3 on 2020-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=64, verbose_name='사용자 비밀번호')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
