# Generated by Django 3.1.4 on 2020-12-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201209_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(related_name='_users_followers_+', to='user.Users'),
        ),
    ]
