# Generated by Django 3.1.4 on 2020-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_users_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='user.Users'),
        ),
    ]
