# Generated by Django 3.1.3 on 2020-11-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_followed_user', to='user.users')),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_following_user', to='user.users')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
    ]
