# Generated by Django 3.0.8 on 2020-07-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='github_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
