# Generated by Django 3.1 on 2020-08-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posting', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
