# Generated by Django 3.0.7 on 2020-07-07 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default=datetime.datetime(2020, 7, 7, 8, 21, 16, 126671, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
