# Generated by Django 3.1.4 on 2021-01-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
