# Generated by Django 3.0.7 on 2020-07-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userid',
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ManyToManyField(blank=True, to='user.User'),
        ),
    ]
