# Generated by Django 3.0.7 on 2020-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200707_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userid',
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
