# Generated by Django 3.1.5 on 2021-02-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='discription',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
