# Generated by Django 3.1.5 on 2021-02-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_posting_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='discription',
            new_name='description',
        ),
    ]
