# Generated by Django 3.1.5 on 2021-02-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
