# Generated by Django 3.0.8 on 2020-07-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20200714_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='email',
        ),
    ]
