# Generated by Django 3.0.8 on 2020-07-16 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200715_1635'),
        ('posting', '0004_article_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='user.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_id', to='posting.Article')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id', to='user.User')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='like', through='posting.Like', to='user.User'),
        ),
    ]
