# Generated by Django 3.0.8 on 2020-07-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200716_1745'),
        ('posting', '0005_auto_20200716_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_article', to='posting.Article'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_user', to='user.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='article_like', through='posting.Like', to='user.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_user', to='user.User'),
        ),
    ]
