# Generated by Django 3.0.8 on 2020-07-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_auto_20200717_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
