# Generated by Django 3.1.7 on 2021-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210311_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='please describe pic', max_length=500),
            preserve_default=False,
        ),
    ]
