# Generated by Django 3.1.5 on 2021-02-01 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210201_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
