# Generated by Django 3.1.5 on 2021-02-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210202_1057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='accounts',
        ),
    ]
