# Generated by Django 3.1.5 on 2021-02-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210204_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user.user')),
            ],
            options={
                'db_table': 'Relationship',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.ManyToManyField(through='user.Relationship', to='user.User'),
        ),
    ]
