# Generated by Django 3.1.4 on 2020-12-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='이메일 주소')),
                ('password', models.CharField(max_length=60, verbose_name='비밀번호')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
