# Generated by Django 3.1.4 on 2020-12-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=1000, verbose_name='비밀번호'),
        ),
    ]
