# Generated by Django 3.0.8 on 2020-07-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_follow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
