# Generated by Django 3.1.5 on 2021-02-01 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210201_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
